### ISSUE TITLE
migrate to EUMM

### ISSUE THREAD

**Issue by plicease** [plicease/Shell-Guess#5]
This would be nice-to-have now but would become a need-to-have if `Alien::Base` ever migrates off of MB.

atm, this module does some fairly simple dynamic prereqs in My::ModuleBuild ... and this could probably be easily ported over to EUMM.

**Comment by simbabque** [comment]
I've got this module in the Pull Request Challenge 2017 and I am looking for stuff to do. It seems you have already done this dae920f3f2097f44e858237b112a3137ff1c6212. Maybe you want to close this issue?

**Comment by plicease** [comment]
Indeed!
